use std::{
    ffi::{OsStr, OsString},
    fs,
    net::{SocketAddr, TcpListener},
    path::{Path, PathBuf},
    process::Command,
};

use crate::{
    config::{Config, DnsConfig},
    errors::{DevhostError, Result},
};

const GENERATED_HEADER: &str =
    "# Generated by devhost. Re-run `devhost install-dns` after DNS config changes.";
const INCLUDE_BEGIN: &str = "# BEGIN devhost dnsmasq include";
const INCLUDE_END: &str = "# END devhost dnsmasq include";

#[derive(Debug)]
pub struct InstallPlan {
    pub dnsmasq_config_path: PathBuf,
    pub dnsmasq_config: String,
    pub dnsmasq_conf_path: PathBuf,
    pub dnsmasq_conf_include: String,
    pub resolver_path: PathBuf,
    pub resolver_config: String,
    pub clean_url_ready: bool,
}

#[derive(Debug)]
pub struct DoctorReport {
    pub checks: Vec<DoctorCheck>,
}

#[derive(Debug)]
pub struct DoctorCheck {
    pub name: &'static str,
    pub ok: bool,
    pub detail: String,
}

impl DoctorReport {
    pub fn has_failures(&self) -> bool {
        self.checks.iter().any(|check| !check.ok)
    }
}

pub fn install(config: &Config, dry_run: bool) -> Result<InstallPlan> {
    let plan = install_plan(config);

    if !dry_run {
        require_root_privileges("install-dns")?;
        write_file(&plan.dnsmasq_config_path, &plan.dnsmasq_config)?;
        ensure_dnsmasq_include(&plan.dnsmasq_conf_path, &plan.dnsmasq_conf_include)?;
        write_file(&plan.resolver_path, &plan.resolver_config)?;
    }

    Ok(plan)
}

pub fn uninstall(config: &Config, dry_run: bool) -> Result<Vec<PathBuf>> {
    let mut touched = Vec::new();
    let paths = [
        config.dns.dnsmasq_config_path.clone(),
        config.dns.resolver_path.clone(),
    ];

    if !dry_run {
        require_root_privileges("uninstall-dns")?;
        for path in &paths {
            remove_generated_file(path)?;
        }

        remove_include_block(&config.dns.dnsmasq_conf_path)?;
    }

    touched.extend(paths);
    touched.push(config.dns.dnsmasq_conf_path.clone());
    Ok(touched)
}

pub fn setup_for_serve(config_path: &Path) -> Result<()> {
    if has_root_privileges() {
        let config = Config::load(config_path)?;
        install(&config, false)?;
    } else {
        let executable = std::env::current_exe()?;
        run_command(
            "sudo",
            [
                executable.as_os_str(),
                OsStr::new("install-dns"),
                OsStr::new("--config"),
                config_path.as_os_str(),
            ],
        )?;
    }

    restart_dnsmasq()
}

pub fn restart_dnsmasq() -> Result<()> {
    if has_root_privileges() {
        run_command(
            "brew",
            [
                OsStr::new("services"),
                OsStr::new("restart"),
                OsStr::new("dnsmasq"),
            ],
        )
    } else {
        run_command(
            "sudo",
            [
                OsStr::new("brew"),
                OsStr::new("services"),
                OsStr::new("restart"),
                OsStr::new("dnsmasq"),
            ],
        )
    }
}

pub fn doctor(config: &Config) -> DoctorReport {
    let mut checks = Vec::new();

    checks.push(command_check(
        "dnsmasq installed",
        "dnsmasq",
        &["--version"],
    ));

    checks.push(DoctorCheck {
        name: "dnsmasq devhost config",
        ok: config.dns.dnsmasq_config_path.exists(),
        detail: config.dns.dnsmasq_config_path.display().to_string(),
    });

    checks.push(DoctorCheck {
        name: "dnsmasq include",
        ok: dnsmasq_conf_includes_devhost(&config.dns),
        detail: config.dns.dnsmasq_conf_path.display().to_string(),
    });

    checks.push(DoctorCheck {
        name: "macOS resolver",
        ok: config.dns.resolver_path.exists(),
        detail: config.dns.resolver_path.display().to_string(),
    });

    checks.push(command_check("dnsmasq running", "pgrep", &["dnsmasq"]));

    checks.push(dns_resolution_check(&config.dns));

    checks.push(proxy_listen_check(config.listen));

    DoctorReport { checks }
}

pub fn install_plan(config: &Config) -> InstallPlan {
    let dnsmasq_config = render_dnsmasq_config(&config.dns);
    let resolver_config = render_resolver_config(&config.dns);
    let dnsmasq_conf_include = render_dnsmasq_include(&config.dns);

    InstallPlan {
        dnsmasq_config_path: config.dns.dnsmasq_config_path.clone(),
        dnsmasq_config,
        dnsmasq_conf_path: config.dns.dnsmasq_conf_path.clone(),
        dnsmasq_conf_include,
        resolver_path: config.dns.resolver_path.clone(),
        resolver_config,
        clean_url_ready: config.listen.port() == 80,
    }
}

pub fn render_dnsmasq_config(dns: &DnsConfig) -> String {
    format!(
        "{GENERATED_HEADER}\naddress=/.{}/{}\nlisten-address={}\nport=53\nbind-interfaces\n",
        dns.tld, dns.loopback_ip, dns.loopback_ip
    )
}

pub fn render_resolver_config(dns: &DnsConfig) -> String {
    format!("{GENERATED_HEADER}\nnameserver {}\n", dns.loopback_ip)
}

fn render_dnsmasq_include(dns: &DnsConfig) -> String {
    let config_dir = dns
        .dnsmasq_config_path
        .parent()
        .unwrap_or_else(|| Path::new("."));
    format!(
        "{INCLUDE_BEGIN}\nconf-dir={},*.conf\n{INCLUDE_END}\n",
        config_dir.display()
    )
}

fn write_file(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }

    fs::write(path, contents)?;
    Ok(())
}

fn ensure_dnsmasq_include(path: &Path, include_block: &str) -> Result<()> {
    let mut contents = fs::read_to_string(path).unwrap_or_default();

    if contents.contains(INCLUDE_BEGIN) {
        contents = replace_marked_block(&contents, include_block);
    } else if !contents.contains(include_block.trim()) {
        if !contents.ends_with('\n') && !contents.is_empty() {
            contents.push('\n');
        }
        contents.push_str(include_block);
    }

    write_file(path, &contents)
}

fn remove_generated_file(path: &Path) -> Result<()> {
    match fs::read_to_string(path) {
        Ok(contents) if contents.starts_with(GENERATED_HEADER) => {
            fs::remove_file(path)?;
        }
        Ok(_) => {}
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
        Err(err) => return Err(err.into()),
    }

    Ok(())
}

fn remove_include_block(path: &Path) -> Result<()> {
    let Ok(contents) = fs::read_to_string(path) else {
        return Ok(());
    };
    let next = remove_marked_block(&contents);
    if next != contents {
        write_file(path, &next)?;
    }

    Ok(())
}

fn dnsmasq_conf_includes_devhost(dns: &DnsConfig) -> bool {
    let Ok(contents) = fs::read_to_string(&dns.dnsmasq_conf_path) else {
        return false;
    };

    if contents.contains(INCLUDE_BEGIN) {
        return true;
    }

    let Some(config_dir) = dns.dnsmasq_config_path.parent() else {
        return false;
    };
    contents.contains(&format!("conf-dir={}", config_dir.display()))
}

fn command_check(name: &'static str, command: &str, args: &[&str]) -> DoctorCheck {
    match Command::new(command).args(args).output() {
        Ok(output) if output.status.success() => DoctorCheck {
            name,
            ok: true,
            detail: command.to_string(),
        },
        Ok(output) => DoctorCheck {
            name,
            ok: false,
            detail: format!("{command} exited with {}", output.status),
        },
        Err(err) => DoctorCheck {
            name,
            ok: false,
            detail: err.to_string(),
        },
    }
}

fn dns_resolution_check(dns: &DnsConfig) -> DoctorCheck {
    let query = format!("devhost-doctor.{}", dns.tld);
    match Command::new("dig")
        .args([
            "+short",
            "+time=1",
            "+tries=1",
            &query,
            &format!("@{}", dns.loopback_ip),
        ])
        .output()
    {
        Ok(output) if output.status.success() => {
            let stdout = String::from_utf8_lossy(&output.stdout);
            let expected = dns.loopback_ip.to_string();
            let ok = stdout.lines().any(|line| line.trim() == expected);
            DoctorCheck {
                name: "dnsmasq resolves local tld",
                ok,
                detail: format!("{query} -> {}", stdout.trim()),
            }
        }
        Ok(output) => DoctorCheck {
            name: "dnsmasq resolves local tld",
            ok: false,
            detail: format!("dig exited with {}", output.status),
        },
        Err(err) => DoctorCheck {
            name: "dnsmasq resolves local tld",
            ok: false,
            detail: err.to_string(),
        },
    }
}

fn proxy_listen_check(listen: SocketAddr) -> DoctorCheck {
    match TcpListener::bind(listen) {
        Ok(listener) => {
            drop(listener);
            DoctorCheck {
                name: "proxy listen address",
                ok: true,
                detail: listen.to_string(),
            }
        }
        Err(err) if err.kind() == std::io::ErrorKind::AddrInUse => DoctorCheck {
            name: "proxy listen address",
            ok: true,
            detail: format!("{listen} already in use"),
        },
        Err(err) if listen.port() < 1024 && err.kind() == std::io::ErrorKind::PermissionDenied => {
            DoctorCheck {
                name: "proxy listen address",
                ok: false,
                detail: format!("{listen} requires root privileges"),
            }
        }
        Err(err) => DoctorCheck {
            name: "proxy listen address",
            ok: false,
            detail: format!("{listen}: {err}"),
        },
    }
}

fn require_root_privileges(command: &str) -> Result<()> {
    if has_root_privileges() {
        return Ok(());
    }

    Err(DevhostError::InvalidConfig(format!(
        "`devhost {command}` writes system DNS files; rerun with sudo or use --dry-run"
    )))
}

fn has_root_privileges() -> bool {
    let Ok(output) = Command::new("id").arg("-u").output() else {
        return false;
    };

    if !output.status.success() {
        return false;
    }

    String::from_utf8_lossy(&output.stdout).trim() == "0"
}

fn run_command<I, S>(program: &str, args: I) -> Result<()>
where
    I: IntoIterator<Item = S>,
    S: AsRef<OsStr>,
{
    let args = args
        .into_iter()
        .map(|arg| arg.as_ref().to_os_string())
        .collect::<Vec<OsString>>();
    let output = Command::new(program).args(&args).output()?;

    if output.status.success() {
        return Ok(());
    }

    let command = std::iter::once(OsString::from(program))
        .chain(args)
        .map(|part| part.to_string_lossy().into_owned())
        .collect::<Vec<_>>()
        .join(" ");
    let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();

    Err(DevhostError::CommandFailed {
        command,
        status: output.status.to_string(),
        stderr,
    })
}

fn replace_marked_block(contents: &str, replacement: &str) -> String {
    let without = remove_marked_block(contents);
    let mut next = without.trim_end().to_string();
    if !next.is_empty() {
        next.push('\n');
    }
    next.push_str(replacement);
    next
}

fn remove_marked_block(contents: &str) -> String {
    let mut output = Vec::new();
    let mut skipping = false;

    for line in contents.lines() {
        if line == INCLUDE_BEGIN {
            skipping = true;
            continue;
        }

        if line == INCLUDE_END {
            skipping = false;
            continue;
        }

        if !skipping {
            output.push(line);
        }
    }

    let mut next = output.join("\n");
    if contents.ends_with('\n') && !next.is_empty() {
        next.push('\n');
    }
    next
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;

    fn config() -> Config {
        Config::from_toml_str(
            r#"
            listen = "127.0.0.1:8080"

            [dns]
            tld = "test"
            loopback_ip = "127.0.0.1"
            dnsmasq_config_path = "/tmp/devhost.conf"
            dnsmasq_conf_path = "/tmp/dnsmasq.conf"
            resolver_path = "/tmp/resolver/test"
            "#,
        )
        .unwrap()
    }

    #[test]
    fn renders_dnsmasq_config_for_tld() {
        let config = config();

        assert_eq!(
            render_dnsmasq_config(&config.dns),
            "# Generated by devhost. Re-run `devhost install-dns` after DNS config changes.\naddress=/.test/127.0.0.1\nlisten-address=127.0.0.1\nport=53\nbind-interfaces\n"
        );
    }

    #[test]
    fn renders_resolver_config() {
        let config = config();

        assert_eq!(
            render_resolver_config(&config.dns),
            "# Generated by devhost. Re-run `devhost install-dns` after DNS config changes.\nnameserver 127.0.0.1\n"
        );
    }

    #[test]
    fn install_plan_knows_when_clean_urls_need_port_80() {
        let config = config();

        assert!(!install_plan(&config).clean_url_ready);
    }

    #[test]
    fn removes_only_marked_include_block() {
        let contents = "keep=true\n# BEGIN devhost dnsmasq include\nconf-dir=/tmp,*.conf\n# END devhost dnsmasq include\nalso=keep\n";

        assert_eq!(remove_marked_block(contents), "keep=true\nalso=keep\n");
    }
}
